name = "worker-template-mysql"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-07"

[build]
command = "npm install && npm run build && cp ./src/driver/**/*.wasm ./dist"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "./dist"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
